### ISSUE TITLE
Use busybox?

### ISSUE THREAD

**Issue by kbrock** [rswier/swieros#1]
Hi,

You may want to take at replacing glibc with [uClib](http://www.uclibc.org/)
And possibly replace your custom commands with [busybox](http://www.busybox.net/)

FWIW/

Keenan

**Comment by rswier** [comment]
Thanks.  I have a few ideas floating around in my head about where I want to take this, but I'm waiting for the ideas to gel.  I recognize that the current design of the library modules (the plan-9'ish u.h/libc.h) does not promote enough cross-fertilization with the "real world."

**Comment by kbrock** [comment]
cool.
I don't know your goals, but saw the word minimal. Even the headers are pretty stripped down.
So thought cutting down on glibc would help. [wikipedia](http://en.wikipedia.org/wiki/GNU_C_Library#Use_in_small_devices) has some good links.

just wanted to make sure that was on your radar.

Funny thing.
When I'm reading this, I keep expecting this to be programmed in go or rust.

Happy Hacking,
Keenan
